package com.luvina.base.core.entity;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

/**
 * Base class for every persistent entity.
 *
 * <p>Provides a UUID primary key, creation/update auditing and a soft-delete flag.
 * Auditing columns are filled automatically: timestamps by Hibernate, user ids by
 * the {@code AuditorAware} bean contributed by {@code common-security}.
 *
 * <p>Rows are never physically removed. Set {@code deleteFlag} to {@code true} and
 * read through the {@code ...DeleteFlagFalse} query methods of
 * {@link com.luvina.base.core.repository.BaseRepository}.
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /** Surrogate primary key, generated by the database as a UUID. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** Id of the user that created the row. Never changes. */
    @CreatedBy
    @Column(name = "created_user_id", updatable = false)
    private UUID createdUserId;

    /** Creation timestamp, set once by Hibernate. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime createdAt;

    /** Id of the user that performed the last update. */
    @LastModifiedBy
    @Column(name = "updated_user_id")
    private UUID updatedUserId;

    /**
     * Last update timestamp. Doubles as the optimistic-lock token exchanged with
     * clients; see {@link com.luvina.base.core.locking.OptimisticLockSupport}.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime updatedAt;

    /** Soft-delete marker. {@code true} means the row is logically removed. */
    @Column(name = "delete_flag", nullable = false)
    private Boolean deleteFlag = Boolean.FALSE;
}
